### ISSUE TITLE
APDE and Ketai doesn't work

### ISSUE THREAD

**Issue by chrmoeller** [ketai/ketai#26]
When you try the code below on an android-smartphone using APDE you'll get the error-message "java.lang.NoSuchMethodError: No virtul method getActivity()Landroid/app/Activity; in class Lprocessing/core/PApplet; or its super classes"
Compiling the same code on a PC and transferring to the smartphone is working well. However coding directly on the smartphone would be nice... What is to do?

=== code ===
import ketai.sensors.*;

KetaiSensor s;

void setup () {
    size(800,600);
    background(255,255,0);
    s = new KetaiSensor ( this ); // This is the line that will break the code! :( :( :(
}
=== end of code ===

**Comment by ketai** [comment]
The Ketai library is focused on hardware affordances that are only available on mobile devices. However, the KetaiSensor class requires the Sensor class included in the Desktop Android SDK in order to compile an app that can run on the mobile device. APDE is not a software development environment that would allow to include the necessary software packages to access hardware sensors and devices.
