### ISSUE TITLE
Both Camera's are flipped

### ISSUE THREAD

**Issue by davidhirotsu** [ketai/ketai#48]
Camera is flipped vertically, across x-axis (not rotated).

In public void settings() I have:
  size(displayWidth, displayHeight, P3D);
  orientation(LANDSCAPE);

In draw() I have:
    image(cam, width/2, height/2, width, height);

Both front and out facing cameras are flipped across the x axis on a Sony Xperia XZ compact, running Nougat, with API 6.0 (23) as target. 

debug:
Found onCameraPreviewEvent 
	842094169
	17
default imageformat:17
No flash support.
Rotation reported: 90
camera: setting display orientation to: 270 degrees
Requested camera parameters as (w,h,fps):1184,720,24
Checking supported preview size:1920,1080
Checking supported preview size:1280,720
Checking supported preview size:720,480
Checking supported preview size:640,480
Checking supported preview size:352,288
Checking supported preview size:320,240
Checking supported preview size:176,144
Supported preview FPS: 15
Supported preview FPS: 30
calculated preview FPS: 15
Calculated camera parameters as (w,h,fps):1280,720,24
Face detection supported!
Using preview format: 17
Preview size: 1280x720,24
Photo size: 1280x720

**Comment by wolfm2** [comment]
Hi davidhirotsu,
  This is likely an issue for a handful of devices that mount the orientation sensor in an uncommon way. A couple years back the Nexus 5X/6 had the same issue with the older camera API leaving it unfortunately for the app developer to fix.  Check out the statement from the Google tech lead below. (from: Reddit)

Best,
Michael
--------------------------------------------------------------------------
 Hi - Tech lead for Android's camera framework here.

Image sensors on a compliant Android device can be mounted in one of two ways. Most devices use one way, so a lot of camera apps have never been tested on devices that pick the other way.

Because of manufacturing reasons, we needed to mount the Nexus 5X main sensor in the less-common (reverse landscape) orientation - the wires from the sensor chip wouldn't have fit otherwise.

...

This is also why a number of apps showed upside down preview on the Nexus 6 front-facing camera last year - it's also in the less-common orientation. But far fewer apps support the front-facing camera than the back-facing one, so it was less of an issue than it is for Nexus 5X.

So if you do see apps with upside-down camera preview on Nexus 5X, please let the developers know about this - Android's developer relations folks are trying to reach out to apps as we find them, and LG is also helping out, but it might take a bit before everyone's up to speed on this issue.
